/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import bd.ProdutoDAO;
import entities.Funcionario;
import entities.Produto;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author diogo
 */
public class TelaBuscarProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaBuscarProduto
     */
    
    private Funcionario funcionario = new Funcionario();
    private Produto produto = new Produto();
    
    public TelaBuscarProduto() {
        initComponents();
    }
    
    public TelaBuscarProduto(Funcionario funcionario) 
    {
        this.funcionario = funcionario;
        produto.setSetor("nenhum"); //flag padrão para verificar se o valor do obj produto foi setado corretamenta pela opção BUSCAR CÓDIGO
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LcodigoNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAsaida = new javax.swing.JTextArea();
        TFcodigoNome = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        cmbBusca = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAtualizarProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Buscar por Produto");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/13.png"))); // NOI18N

        LcodigoNome.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        LcodigoNome.setText("Nome/Código do Produto:");

        TAsaida.setColumns(20);
        TAsaida.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        TAsaida.setRows(5);
        TAsaida.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(TAsaida);

        TFcodigoNome.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 57, 23));
        btnVoltar.setText("<<");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        cmbBusca.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        cmbBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUSCAR TODOS", "BUSCAR POR NOME", "BUSCAR POR CÓDIGO" }));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(249, 154, 8));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        btnAtualizarProduto.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        btnAtualizarProduto.setText("Atualizar dados Produto");
        btnAtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LcodigoNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFcodigoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cmbBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnAtualizarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LcodigoNome)
                    .addComponent(TFcodigoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(cmbBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnAtualizarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        if(funcionario.getSetor().equals("Administração"))
        {
            TelaInicialAdmin tc = new TelaInicialAdmin(funcionario);
            tc.setVisible(true);
            this.dispose();
        }
        else
        {
            TelaInicial tc = new TelaInicial(funcionario);
            tc.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        if (cmbBusca.getSelectedItem().toString().equals("BUSCAR TODOS"))
        {
            List<Produto> produtos = new ArrayList<>();
            ProdutoDAO pDAO = new ProdutoDAO();
            produtos = pDAO.listarTodosProdutos(produto);
            
            String resultado = "Dados básicos de todos os produtos:\n\n";
            for (Produto p : produtos){
                resultado += "Nome: " + p.getNome() + "\n";
                //resultado += "Marca: " + p.getMarca()+ "\n";
                resultado += "Código: " + p.getCodigo() + "\n\n";
                //resultado += "Preço: " + p.getPreco()+ "\n";
                //resultado += "Validade: " + dateFormat.format(p.getValidade())+ "\n";
                //resultado += "Setor: " + p.getSetor()+ "\n";
               // resultado += "Quantidade em Estoque: " + p.getQuantidade()+ "\n";
                //resultado += "Lote: " + p.getLote()+ "\n\n\n";
            }
            
            TAsaida.setText(resultado);
        }
        else if (cmbBusca.getSelectedItem().toString().equals("BUSCAR POR NOME"))
        {
            produto.setNome(TFcodigoNome.getText());
            if(TFcodigoNome.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Digite o Nome ou código do produto!");
            }
            else
            {
                List<Produto> produtos = new ArrayList<>();
                ProdutoDAO pDAO = new ProdutoDAO();
                produtos = pDAO.listarNomeProdutos(produto);

                String resultado = "Dados dos Produtos:\n\n";
                for (Produto p : produtos){
                    resultado += "Nome: " + p.getNome() + "\n";
                    resultado += "Marca: " + p.getMarca()+ "\n";
                    resultado += "Código: " + p.getCodigo() + "\n";
                    resultado += "Preço: " + p.getPreco()+ "\n";
                    resultado += "Validade: " + dateFormat.format(p.getValidade())+ "\n";
                    resultado += "Setor: " + p.getSetor()+ "\n";
                    resultado += "Quantidade em Estoque: " + p.getQuantidade()+ "\n";
                    resultado += "Lote: " + p.getLote()+ "\n\n\n";
                }

                TAsaida.setText(resultado);
            }
        }
        else
        {
            produto.setCodigo(Integer.valueOf(TFcodigoNome.getText()));
            if(TFcodigoNome.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Digite o Nome ou código do produto!");
            }
            else
            {
                List<Produto> produtos = new ArrayList<>();
                ProdutoDAO pDAO = new ProdutoDAO();
                produtos = pDAO.listarCodigoProdutos(produto);

                String resultado = "Dados dos produtos:\n\n";
                for (Produto p : produtos){
                    resultado += "-------------------------------------\n";
                    resultado += "Nome: " + p.getNome() + "\n";
                    resultado += "-------------------------------------\n";
                    resultado += "Marca: " + p.getMarca()+ "\n";
                    resultado += "-------------------------------------\n";
                    resultado += "Código: " + p.getCodigo() + "\n";
                    resultado += "-------------------------------------\n";
                    resultado += "Preço: " + p.getPreco()+ "\n";
                    resultado += "-------------------------------------\n";
                    resultado += "Validade: " + dateFormat.format(p.getValidade())+ "\n";
                    resultado += "-------------------------------------\n";
                    resultado += "Setor: " + p.getSetor()+ "\n";
                    resultado += "-------------------------------------\n";
                    resultado += "Quantidade em Estoque: " + p.getQuantidade()+ "\n";
                    resultado += "-------------------------------------\n";
                    resultado += "Lote: " + p.getLote()+ "\n";
                    resultado += "-------------------------------------\n\n";
                }

                TAsaida.setText(resultado);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarProdutoActionPerformed
       
        if (produto.getSetor().equals("nenhum"))
        {
            JOptionPane.showMessageDialog(null, "Produto não encontrado. Selecione a opção BUSCAR POR CÓDIGO!");
        }
        else
        {
            TelaAtualizarProduto tap = new TelaAtualizarProduto(funcionario, produto);
            tap.setVisible(true);
            this.dispose();
        }
   
    }//GEN-LAST:event_btnAtualizarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LcodigoNome;
    private javax.swing.JTextArea TAsaida;
    private javax.swing.JTextField TFcodigoNome;
    private javax.swing.JButton btnAtualizarProduto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
