/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import bd.ProdutoDAO;
import entities.Funcionario;
import entities.Produto;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author diogo
 */
public class TelaBuscarProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaBuscarProduto
     */
    
    private Funcionario funcionario = new Funcionario();
    
    public TelaBuscarProduto() {
        initComponents();
    }
    
    public TelaBuscarProduto(Funcionario funcionario) 
    {
        this.funcionario = funcionario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LcodigoNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAsaida = new javax.swing.JTextArea();
        TFcodigoNome = new javax.swing.JTextField();
        Lvoltar = new javax.swing.JButton();
        cmbBusca = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Buscar por Produto");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("buscar produto");

        LcodigoNome.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        LcodigoNome.setText("Nome/Código do Produto:");

        TAsaida.setColumns(20);
        TAsaida.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        TAsaida.setRows(5);
        TAsaida.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(TAsaida);

        TFcodigoNome.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N

        Lvoltar.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        Lvoltar.setText("Voltar");
        Lvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LvoltarActionPerformed(evt);
            }
        });

        cmbBusca.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        cmbBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUSCAR TODOS", "BUSCAR POR NOME", "BUSCAR POR CÓDIGO" }));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(LcodigoNome)
                        .addGap(34, 34, 34)
                        .addComponent(TFcodigoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lvoltar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LcodigoNome)
                    .addComponent(TFcodigoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Lvoltar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LvoltarActionPerformed
        // TODO add your handling code here:
        if(funcionario.getSetor().equals("Administração"))
        {
            TelaInicialAdmin tc = new TelaInicialAdmin(funcionario);
            tc.setVisible(true);
            this.dispose();
        }
        else
        {
            TelaInicial tc = new TelaInicial(funcionario);
            tc.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LvoltarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Produto produto = new Produto();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        if (cmbBusca.getSelectedItem().toString().equals("BUSCAR TODOS"))
        {
            List<Produto> produtos = new ArrayList<>();
            ProdutoDAO pDAO = new ProdutoDAO();
            produtos = pDAO.listarTodosProdutos(produto);
            
            String resultado = "Dados básicos de todos os produtos:\n\n";
            for (Produto p : produtos){
                resultado += "Nome: " + p.getNome() + "\n";
                //resultado += "Marca: " + p.getMarca()+ "\n";
                resultado += "Código: " + p.getCodigo() + "\n\n";
                //resultado += "Preço: " + p.getPreco()+ "\n";
                //resultado += "Validade: " + dateFormat.format(p.getValidade())+ "\n";
                //resultado += "Setor: " + p.getSetor()+ "\n";
               // resultado += "Quantidade em Estoque: " + p.getQuantidade()+ "\n";
                //resultado += "Lote: " + p.getLote()+ "\n\n\n";
            }
            
            TAsaida.setText(resultado);
        }
        else if (cmbBusca.getSelectedItem().toString().equals("BUSCAR POR NOME"))
        {
            produto.setNome(TFcodigoNome.getText());
            if(TFcodigoNome.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Digite o Nome ou código do produto!");
            }
            else
            {
                List<Produto> produtos = new ArrayList<>();
                ProdutoDAO pDAO = new ProdutoDAO();
                produtos = pDAO.listarNomeProdutos(produto);

                String resultado = "Dados dos Produtos:\n\n";
                for (Produto p : produtos){
                    resultado += "Nome: " + p.getNome() + "\n";
                    resultado += "Marca: " + p.getMarca()+ "\n";
                    resultado += "Código: " + p.getCodigo() + "\n";
                    resultado += "Preço: " + p.getPreco()+ "\n";
                    resultado += "Validade: " + dateFormat.format(p.getValidade())+ "\n";
                    resultado += "Setor: " + p.getSetor()+ "\n";
                    resultado += "Quantidade em Estoque: " + p.getQuantidade()+ "\n";
                    resultado += "Lote: " + p.getLote()+ "\n\n\n";
                }

                TAsaida.setText(resultado);
            }
        }
        else
        {
            produto.setCodigo(Integer.valueOf(TFcodigoNome.getText()));
            if(TFcodigoNome.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Digite o Nome ou código do produto!");
            }
            else
            {
                List<Produto> produtos = new ArrayList<>();
                ProdutoDAO pDAO = new ProdutoDAO();
                produtos = pDAO.listarCodigoProdutos(produto);

                String resultado = "Dados dos produtos:\n\n";
                for (Produto p : produtos){
                    resultado += "Nome: " + p.getNome() + "\n";
                    resultado += "Marca: " + p.getMarca()+ "\n";
                    resultado += "Código: " + p.getCodigo() + "\n";
                    resultado += "Preço: " + p.getPreco()+ "\n";
                    resultado += "Validade: " + dateFormat.format(p.getValidade())+ "\n";
                    resultado += "Setor: " + p.getSetor()+ "\n";
                    resultado += "Quantidade em Estoque: " + p.getQuantidade()+ "\n";
                    resultado += "Lote: " + p.getLote()+ "\n\n\n";
                }

                TAsaida.setText(resultado);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LcodigoNome;
    private javax.swing.JButton Lvoltar;
    private javax.swing.JTextArea TAsaida;
    private javax.swing.JTextField TFcodigoNome;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
